version: '3'

services:
    postgres:
        container_name: 'stonks-api-postgres'
        build:
            context: ./.docker/postgres
            dockerfile: Dockerfile
        restart: always
        shm_size: 4g
        ports:
            - 5445:5432
        volumes:
            - "./.docker/postgres/data:/var/lib/postgresql/data:rw"
        environment:
            - POSTGRES_DB=stonks_api
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - PGDATA=/var/lib/postgresql/data
            - POSTGRES_HOST_AUTH_METHOD=trust

    php:
        build: .docker/php
        container_name: 'stonks-api-php'
        volumes:
            - .:/var/www/html/stonks-api
        links:
            - postgres
        depends_on:
            - php-build

    php-build:
        image: php
        build: .docker/php
        container_name: 'stonks-api-php-build'
        volumes:
            - .:/var/www/html/stonks-api
        links:
            - postgres
        command: >
            bash -c "cd /var/www/html/stonks-api && composer setup"

    php-worker:
        image: php
        build: .docker/php
        container_name: 'stonks-api-php-worker'
        volumes:
            - .:/var/www/html/stonks-api
        links:
            - postgres
        depends_on:
            - php-build
        command: >
            bash -c "cd /var/www/html/stonks-api && php artisan queue:work"

    nginx:
        build:
            context: .docker
            dockerfile: nginx/Dockerfile
        container_name: 'stonks-api-nginx'
        ports:
            - 8019:80
        depends_on:
            - php
        volumes:
            - .:/var/www/html/stonks-api

volumes:
    postgres:
        driver: local
    php:
        driver: local
    redis:
        driver: local
